services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - nexus_network

volumes:
    nexus_data:
      driver: local

networks:
  nexus_network:
    driver: bridge