---
- name: Include Docker installation tasks
  include_tasks: "{{ role_path }}/../common/tasks/docker-rhel.yml"

- name: Update the maximum number of memory map areas
  shell: |
    echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
    sudo sysctl -p

- name: Synchronize SonarQube config folder
  synchronize:
    src: "{{ role_path }}/files/"
    dest: "/home/{{ ansible_user }}/sonarqube/"
    recursive: yes

- name: Start SonarQube Compose
  command:
    cmd: "docker compose -f docker-compose.sonarqube.yml up -d"
    chdir: "/home/{{ ansible_user }}/sonarqube"





